#!/bin/bash
# Author   : Samiux (https://www.infosec-ninjas.com)
# Date     : JUL 20, 2017
# License  : GPLv3 (Open Source)

# get variables from nsm.conf
. /etc/croissants/conf.d/nsm.conf

NAT_IP=""
BASEIP=""

# fetch gateway ip address
IP=$(route -n | grep 'UG[ \t]' | awk '{print $2}')
TEST=`echo "${IP}." | grep -E "([0-9]{1,3}\.){4}"`

if [ "$TEST" ]
then
	BASEIP=$(echo $IP | cut -d"." -f1-3)
	NAT_IP=$BASEIP"."$INF_MONITORING_NAT
  if [[ "$INF_MONITORING_IP" != "$NAT_IP" ]]; then
	  sudo sed -i 's/INF_MONITORING_IP=.*/INF_MONITORING_IP=\"'$NAT_IP'\"/g' /etc/croissants/conf.d/nsm.conf
		sudo sed -i 's/INF_GATEWAY=.*/INF_GATEWAY=\"'$IP'\"/g' /etc/croissants/conf.d/nsm.conf
		sudo /etc/croissants/conf.d/auto_network_config
	else
		if [[ "$IP" != "$INF_MONITORING_IP" ]]; then
			sudo /etc/croissants/conf.d/auto_network_config
		fi
	fi
fi
