#!/bin/bash

# Author    : Samiux (https://samiux.github.io)
# Date      : DEC 22, 2020
# License   : GPLv3 (Open Source)

# check the last 100 line of log to see if there is any drops detected.  if so, restart suricata

# first delete all zombie processes
sudo ps -xaw -o state,ppid | grep Z | grep -v PID | awk '{ print $2 }' | xargs -r sudo kill -9

# check drops
sudo tail -100 /var/log/suricata/stats.log | grep drop 2>/dev/null 1>/dev/null
if [ "$?" -ne 1 ]
then
        echo "Drops detected, restarting suricata ...."
        dt=$(date '+%d/%m/%Y %H:%M:%S')
        echo "$dt" " Suricata restart!" | sudo tee -a /var/log/suricata/drop_stats.log
        sudo systemctl restart suricata
        echo "suricata restarted!"
else
        echo "No drop detected!"
#        dt=$(date '+%d/%m/%Y %H:%M:%S')
#        echo "$dt" " No drop!" | sudo tee -a /var/log/suricata/drop_stats.log
fi
