#!/bin/bash
# Author   : Samiux (https://samiux.github.io)
# Date     : JUL 20, 2017
# License  : GPLv3 (Open Source)

sudo cp /etc/suricata/drop.conf_sample /etc/suricata/
sudo cp /etc/suricata/drop.conf_sample /etc/suricata/drop.conf
sudo cp /etc/suricata/disable.conf_sample /etc/suricata/
sudo cp /etc/suricata/disable.conf_sample /etc/suricata/disable.conf
sudo cp /etc/suricata/enable.conf_sample /etc/suricata/
sudo cp /etc/suricata/enable.conf_sample /etc/suricata/enable.conf
sudo cp /etc/suricata/modify.conf_sample /etc/suricata/
sudo cp /etc/suricata/modify.conf_sample /etc/suricata/modify.conf

sudo /usr/bin/nsm_rules_update
