#!/bin/bash
# Author   : Samiux (https://samiux.github.io)
# Date     : DEC 22, 2020
# License  : GPLv3 (Open Source)

# for self-sign cert rule
cd /tmp
git clone https://github.com/StamusNetworks/stamus-luajit-scripts.git
#sudo cp stamus-luajit-scripts/*.lua /etc/suricata/rules/
sudo cp stamus-luajit-scripts/*.lua /var/lib/suricata/rules/

# set up 3rd party ip blocking list
#
# zeustracker.abuse.ch
#
cd /tmp
wget https://zeustracker.abuse.ch/blocklist.php?download=badips -O /tmp/zeustracker.txt
if [ -s /tmp/zeustracker.txt ]
then
	grep -v "#" /tmp/zeustracker.txt | grep -v " " /tmp/zeustracker.txt | grep -v "" /tmp/zeustracker.txt | sort -u | sed -e 's/$/,1,10/' > /var/lib/suricata/rules/iprep/zeustracker.blacklist
fi

#
# blocklist.de
#
cd /tmp
wget https://lists.blocklist.de/lists/dnsbl/allinone.list -O /tmp/allinone.list
if [ -s /tmp/allinone.list ]
then
	sed 's/:.*//' /tmp/allinone.list | sed -e '/^\s*$/d' | sort -u | sed -e 's/$/,1,10/' > /var/lib/suricata/rules/iprep/blocklist.de.blacklist
fi

#
# IPBLC Server IP Blacklist
#
cd /tmp
wget http://www.ip-finder.me/ip-full-list/ -O /tmp/ip-finder.me.html
if [ -s /tmp/ip-finder.me.html ]
then
	grep -P -o '(?<=/)[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}(?=/)' /tmp/ip-finder.me.html | sort -u | sed -e 's/$/,1,10/' > /var/lib/suricata/rules/iprep/ip-finder.blacklist
fi

#
# TOR Exit Nodes
#
cd /tmp
wget https://check.torproject.org/cgi-bin/TorBulkExitList.py?ip=1.1.1.1 -O TorBulkExitList
if [ -s /tmp/TorBulkExitList ]
then
	sed -i "/^#/d" /tmp/TorBulkExitList
	cat /tmp/TorBulkExitList | sort -u | sed -e 's/$/,2,10/' > /var/lib/suricata/rules/iprep/tor.torexitnode
fi

#
# idps.rules
#
cd /tmp
wget https://github.com/samiux/update-croissants/raw/master/rules/idps.rules -O /tmp/idps.rules
if [ -s /tmp/idps.rules ]
then
	sudo cp /tmp/idps.rules /var/lib/suricata/rules/

fi

#
# scanners.rules
#
cd /tmp
wget https://github.com/samiux/update-croissants/raw/master/rules/scanners.rules -O /tmp/scanners.rules
if [ -s /tmp/scanners.rules ]
then
	sudo cp /tmp/scanners.rules /var/lib/suricata/rules/

fi

#
# malware_md5
#
cd /tmp
wget https://github.com/samiux/update-croissants/raw/master/rules/malware_md5 -O /tmp/malware_md5
if [ -s /tmp/malware_md5 ]
then
	sudo cp /tmp/malware_md5 /var/lib/suricata/rules/
fi

cd /tmp
wget https://github.com/samiux/update-croissants/raw/master/rules/reputation.blacklist -O /tmp/reputation.blacklist
if [ -s /tmp/reputation.blacklist ]
then
	sudo cp /tmp/reputation.blacklist /var/lib/suricata/rules/iprep/
fi

cd /tmp
wget https://github.com/samiux/update-croissants/raw/master/rules/malicious.url -O /tmp/malicious.url
if [ -s /tmp/malicious.url ]
then
	sudo cp /tmp/malicious.url /var/lib/suricata/rules/
fi

#
# ransomware tracker
#
cd /tmp
wget http://ransomwaretracker.abuse.ch/downloads/RW_DOMBL.txt -O /tmp/RW_DOMBL.txt
if [ -s /tmp/RW_DOMBL.txt ]
then
	grep -v "#" /tmp/RW_DOMBL.txt > /var/lib/suricata/rules/ransomwaretracker.url
fi

cd /tmp
wget http://ransomwaretracker.abuse.ch/downloads/RW_URLBL.txt -O /tmp/RW_URLBL.txt
if [ -s /tmp/RW_URLBL.txt ]
then
	grep -v "#" /tmp/RW_URLBL.txt >> /var/lib/suricata/rules/ransomwaretracker.url
fi

cd /tmp
wget http://ransomwaretracker.abuse.ch/downloads/RW_IPBL.txt -O /tmp/RW_IPBL.txt
if [ -s /tmp/RW_IPBL.txt ]
then
	grep -v "#" RW_IPBL.txt | sort -u | sed -e 's/$/,1,10/' > /var/lib/suricata/rules/iprep/ransomwaretracker.blacklist
fi

#
# various malware sha1 and sha256 checksum
#
cd /tmp
wget https://github.com/samiux/update-croissants/raw/master/rules/malware_sha1 -O /tmp/malware_sha1
if [ -s /tmp/malware_sha1 ]
then
  sudo cp /tmp/malware_sha1 /var/lib/suricata/rules/
fi

cd /tmp
wget https://github.com/samiux/update-croissants/raw/master/rules/malware_sha256 -O /tmp/malware_sha256
if [ -s /tmp/malware_sha256 ]
then
  sudo cp /tmp/malware_sha256 /var/lib/suricata/rules/
fi

#
# sslbl.abuse.ch blacklist
#
cd /tmp
wget https://sslbl.abuse.ch/blacklist/ja3_fingerprints.rules -O /tmp/ja3_fingerprints.rules
if [ -s /tmp/ja3_fingerprints.rules ]
then
  sudo sed -i 's/alert/reject/' /tmp/ja3_fingerprints.rules
  # disable Tencent SSL cert
  sudo sed -i 's/.*906200038/#&/' /tmp/ja3_fingerprints.rules  
  sudo cp /tmp/ja3_fingerprints.rules /var/lib/suricata/rules/
fi

wget https://sslbl.abuse.ch/blacklist/sslipblacklist.rules -O /tmp/sslipblacklist.rules
if [ -s /tmp/sslipblacklist.rules ]
then
  sudo sed -i 's/alert/reject/' /tmp/sslipblacklist.rules
  sudo cp /tmp/sslipblacklist.rules /var/lib/suricata/rules/
fi

wget https://sslbl.abuse.ch/blacklist/sslblacklist_tls_cert.rules -O /tmp/sslblacklist_tls_cert.rules
if [ -s /tmp/sslblacklist_tls_cert.rules ]
then
  sudo sed -i 's/alert/reject/' /tmp/sslblacklist_tls_cert.rules
  sudo cp /tmp/sslblacklist_tls_cert.rules /var/lib/suricata/rules/
fi

#
# Phishing Database
#
wget https://raw.githubusercontent.com/mitchellkrogza/Phishing.Database/master/phishing-links-ACTIVE.txt -O /tmp/phishing-links-ACTIVE.txt
if [ -s /tmp/phishing-links-ACTIVE.txt ]
then
  sed -i 's/http:\/\///' /tmp/phishing-links-ACTIVE.txt
  mv /tmp/phishing-links-ACTIVE.txt /tmp/phishing.url
  sudo cp /tmp/phishing.url /var/lib/suricata/rules/
fi

#
# Hacked Domains with Malware
#
wget https://raw.githubusercontent.com/mitchellkrogza/The-Big-List-of-Hacked-Malware-Web-Sites/master/hacked-domains.list -O /tmp/hacked-domains.list
if [ -s /tmp/hacked-domains.list ]
then
  mv /tmp/hacked-domains.list /tmp/hacked-domains.url
  sudo cp /tmp/hacked-domains.url /var/lib/suricata/rules/
fi

# cleaning up
sudo rm -R stamus-luajit-scripts
sudo rm /tmp/*.blf
sudo rm /tmp/*.txt
sudo rm /tmp/*.list
sudo rm /tmp/*.csv
sudo rm /tmp/*.html
sudo rm /tmp/*.blacklist
sudo rm /tmp/*.rules*
sudo rm /tmp/*.tar.gz*
sudo rm /tmp/*.bz2
sudo rm /tmp/*.url
sudo rm /tmp/crypt*
sudo rm /tmp/malware*
sudo rm -R /tmp/rules/
cd ~

# loading rules
sudo suricata-update
sudo kill -USR2 $(pidof suricata)

# workaround to fix minor bug of suricata for memory leaking on every reload (-USR2)
sudo sync; sudo sh -c 'echo 3 > /proc/sys/vm/drop_caches'
